name: derekclair
favicon: null
layout_spectrum: 0
typography_spectrum: 0.60034
title: A gentleman and a scholar.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-5175648-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7243723687715828
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
