name: Derek Clair
favicon: null
layout_spectrum: 1
typography_spectrum: 0.28631
title: A gentleman and a scholar.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-5175648-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9d9c9a'
    - '#6c6b69'
    - '#444341'
    - '#020202'
    - '#fafafa'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
